title: "Foundations of ML Vision"
description: "A comprehensive guide to building and deploying modern ML vision models."
baseurl: "/the-ml-vision-book"
url: "https://rightedges.github.io"

remote_theme: just-the-docs/just-the-docs

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme settings
color_scheme: light # Optional: Dark mode by default
search_enabled: true
aux_links:
  "View on GitHub":
    - https://github.com/rightedges/the-ml-vision-book

# Exclude unnecessary files
exclude:
  - docs/
  - node_modules/
  - package.json
  - package-lock.json
  - vendor/
  - Gemfile
  - Gemfile.lock
  - .github/
